export interface Menu {
  // 菜品分类
  category: string
  // 菜品列表
  list: Item[]
}

export interface Item {
  // 菜id
  id: number
  // 菜名
  name: string
  // 辣度
  spicy?: number
  // 是否新品
  new?: boolean
  // 容量
  capacity?: number
  // 人气
  top?: boolean
  // 冷菜
  cold?: boolean
  // 推荐
  recommend?: boolean
  // 描述
  desc?: string
  // 价格
  price: number
}

// 萨莉亚菜品
export const menu: Menu[] = [{
  category: "新品",
  list: [{
    id: 1017,
    name: "熟制虾仁沙拉",
    new: true,
    price: 15,
    desc: "熟制虾仁搭配新鲜蔬菜与萨莉亚特制沙拉酱的结合",
  }, {
    id: 1254,
    name: "小份虾仁配沙拉酱",
    new: true,
    price: 9,
  }, {
    id: 1297,
    name: "蒜香黄油蜗牛配面包片",
    new: true,
    price: 18,
    desc: "蒜香黄油蜗牛搭配面包片的组合，更美味",
  }, {
    id: 1250,
    name: "蒜香黄油炒菜心",
    new: true,
    price: 9,
    desc: "蒜香黄油与清甜爽口菜心的结合",
  }, {
    id: 1255,
    name: "橄榄油炒西葫芦",
    new: true,
    price: 9,
  }, {
    id: 1253,
    name: "芝士烤菠菜",
    new: true,
    price: 9,
    desc: "鲜嫩多汁的菠菜与香浓芝士的结合",
  }, {
    id: 1256,
    name: "芝士培根焗西葫芦",
    new: true,
    price: 13,
  }, {
    id: 1218,
    name: "原味煮花蛤",
    new: true,
    price: 13,
    desc: "地中海式原始美味",
  }, {
    id: 1396,
    name: "鸡肉培根小匹萨",
    new: true,
    price: 15,
  }, {
    id: 1395,
    name: "金枪鱼小匹萨",
    new: true,
    price: 15,
    desc: "金枪鱼、玉米与芝士的融合",
  }, {
    id: 1314,
    name: "金枪鱼匹萨",
    new: true,
    price: 26,
    desc: "金枪鱼、玉米与芝士的融合",

  }, {
    id: 1428,
    name: "曙光女神酱烩饭",
    new: true,
    price: 16,
  }, {
    id: 1543,
    name: "曙光女神酱意面",
    new: true,
    price: 16,
    desc: "萨莉亚特制曙光女神酱搭配芝士和菜心",

  }, {
    id: 1620,
    name: "蒜香黄油烤鱼排",
    new: true,
    price: 21,
    desc: "蒜香黄油搭配鱼排，鲜香可口",

  }, {
    id: 1618,
    name: "黑椒汉堡",
    new: true,
    price: 23,
    desc: "浇有黑椒酱汁、口味平衡香浓",

  }, {
    id: 1619,
    name: "芝士汉堡",
    new: true,
    price: 27,
    desc: "浓浓芝士、番茄酱和汉堡的组合",

  }, {
    id: 1735,
    name: "肉桂糖烤饼配香草冰激凌",
    new: true,
    price: 10,
    desc: "散发着香甜肉桂气息的现烤饼底，搭配冰凉香草味冰激凌，感受冷,热变化的味觉体验"

  }, {
    id: 1908,
    name: "普里米蒂沃干红葡萄酒",
    capacity: 187,
    price: 18,
    desc: "普利亚地区出品，香气浓郁，口感圆润悠长。",

  }, {
    id: 1909,
    name: "维罗纳干白葡萄酒",
    capacity: 187,
    price: 18,
    desc: "威尼托产区出品，有清新水果和鲜花的芬芳。",
  }]
}, {
  category: "人气商品",
  list: [{
    id: 1011,
    name: "金枪鱼沙拉",
    top: true,
    price: 11,
    desc: "富含不饱和脂肪酸、DHA的金枪鱼，营养美味健康",
  }, {
    id: 1116,
    name: "蘑菇汤",
    price: 9,
    desc: "浓浓蘑菇香，回味无穷",
  }, {
    id: 1230,
    name: "人气小吃拼盘①",
    new: true,
    price: 27,
    desc: "鸡翅、鸡排串、鸡肉粒等人气小吃的拼盘，享受分享的乐趣",
  }, {
    id: 1231,
    name: "人气小吃拼盘②",
    top: true,
    price: 27,
    desc: "鸡翅、鸡米花、烤肠等人气小吃的拼盘",
  }, {
    id: 1208,
    name: "意式茄红鸡翅",
    recommend: true,
    price: 26,
    desc: "皮酥肉嫩、不容错过的意式美味",
  }, {
    id: 1235,
    name: "鱿鱼花蛤拼盘",
    price: 26,
    desc: "花蛤与烤鱿鱼的人气组合",
  }, {
    id: 1297,
    name: "蒜香黄油蜗牛配面包片",
    new: true,
    price: 18,
    desc: "蒜香黄油蜗牛搭配面包片的组合，更美味",
  }, {
    id: 1387,
    name: "榴莲小匹萨",
    recommend: true,
    price: 21,
    desc: "进口金枕头榴莲与芝士的结合",
  }, {
    id: 1501,
    name: "肉酱意面",
    price: 18,
    desc: "满满的肉酱，意式风味（含猪牛肉）",
  }, {
    id: 1513,
    name: "黑椒牛柳意面",
    price: 18,
    desc: "中西结合、人气美味",
  }, {
    id: 1509,
    name: "番茄海鲜意面",
    price: 22,
    desc: "虾、花蛤、鱿鱼组成的海鲜盛宴",
  }, {
    id: 1607,
    name: "鸡翅鸡排牛肉粒拼盘",
    price: 49,
    desc: "鸡翅、鸡排及牛肉粒的组合，肉的盛宴",
  }, {
    id: 1613,
    name: "烘烤羊排(2根)",
    price: 49,
    desc: "精选羔羊羊排、原味烤制",
  }, {
    id: 1888,
    name: "畅饮",
    price: 8,
    desc: "一人畅饮只限一人独享，不可外带",
  }]
}, {
  category: "沙拉、汤",
  list: [{
    id: 1017,
    name: "熟制虾仁沙拉",
    new: true,
    price: 15,
  }, {
    id: 1011,
    name: "金枪鱼沙拉",
    recommend: true,
    price: 11,
    desc: "富含不饱和脂肪酸、DHA的金枪鱼，营养美味健康",
  }, {
    id: 1012,
    name: "水果沙拉",
    price: 9,
    desc: "水果与蔬菜的精致组合，口感鲜甜，富含多种维生素",
  }, {
    id: 1013,
    name: "海带丝沙拉",
    price: 9,
    desc: "尊贵不贵，健康美味",
  }, {
    id: 1014,
    name: "玉米沙拉",
    price: 9,
    desc: "清甜玉米与田园蔬菜的简单搭配",
  }, {
    id: 1116,
    name: "蘑菇汤",
    price: 9,
    desc: "浓浓蘑菇香，回味无穷",
  }, {
    id: 1115,
    name: "玉米汤",
    price: 9,
    desc: "香浓的玉米汤汁在口里融化开来",
  }, {
    id: 1117,
    name: "田园蔬菜汤",
    price: 9,
    desc: "各种新鲜蔬菜熬制，田园风味的番茄蔬菜汤（含少许猪肉碎）",
  }, {
    id: 1114,
    name: "花蛤汤",
    top: true,
    price: 9,
    desc: "来自大海的味道，清爽鲜甜",
  }]
}, {
  category: "前菜",
  list: [{
    id: 1230,
    name: "人气小吃拼盘①",
    new: true,
    price: 27,
    desc: "鸡翅、鸡排串、鸡肉粒等人气小吃的拼盘，享受分享的乐趣",
  }, {
    id: 1231,
    name: "人气小吃拼盘②",
    top: true,
    price: 27,
    desc: "鸡翅、鸡米花、烤肠等人气小吃的拼盘",
  }, {
    id: 1235,
    name: "鱿鱼花蛤拼盘",
    price: 26,
    desc: "花蛤与烤鱿鱼的人气组合",
  }, {
    id: 1250,
    name: "蒜香黄油炒菜心",
    new: true,
    price: 9,
    desc: "蒜香黄油与清甜爽口菜心的结合",
  }, {
    id: 1229,
    name: "芝士烤玉米",
    price: 9,
    desc: "玉米与芝士香味扑鼻，回味无穷",
  }, {
    id: 1253,
    name: "芝士烤菠菜",
    new: true,
    price: 9,
    desc: "鲜嫩多汁的菠菜与香浓芝士的结合",
  }, {
    id: 1255,
    name: "橄榄油炒西葫芦",
    new: true,
    price: 9,
  }, {
    id: 1290,
    name: "蒜香花椰菜",
    price: 9,
  }, {
    id: 1240,
    name: "海带丝",
    cold: true,
    price: 9,
    desc: "海中美味、凉拌佳肴",
  }, {
    id: 1254,
    name: "小份虾仁配沙拉酱",
    new: true,
    price: 9,
  }, {
    id: 1289,
    name: "什锦鲜蔬",
    price: 12,
  }, {
    id: 1226,
    name: "烤甜玉米",
    price: 7,
    desc: "自然的玉米香，甜美可口",
  }, {
    id: 1224,
    name: "烤菠菜",
    price: 7,
    desc: "鲜嫩多汁的家常小菜",
  }, {
    id: 1204,
    name: "QQ薯角",
    price: 7,
    desc: "天然马铃薯经烤箱烘烤，有效控制热量",
  }, {
    id: 1256,
    name: "芝士培根局西葫芦",
    new: true,
    price: 13,
  }, {
    id: 1297,
    name: "蒜香黄油蜗牛配面包片",
    new: true,
    price: 18,
    desc: "蒜香黄油蜗牛搭配面包片的组合，更美味",
  }, {
    id: 1208,
    name: "意式茄红鸡翅",
    recommend: true,
    price: 26,
    desc: "皮酥肉嫩、不容错过的意式美味",
  }, {
    id: 1246,
    name: "椒盐鸡腿排",
    price: 16,
    desc: "精选鸡肉，皮脆肉嫩，香嫩多汁",
  }, {
    id: 1234,
    name: "五目烤肠",
    price: 16,
    desc: "加入田园鲜蔬，外脆内嫩",
  }, {
    id: 1233,
    name: "黑椒烤肠",
    price: 16,
    desc: "黑胡椒风味，外脆内嫩",
  }, {
    id: 1232,
    name: "盐酥鸡肉粒",
    price: 13,
    desc: "外酥里嫩，咸香美味",
  }, {
    id: 1275,
    name: "奶油土豆泥",
    price: 13,
    desc: "土豆泥中融入奶油沙司与浓香芝士粉",
  }, {
    id: 1218,
    name: "原味煮花蛤",
    new: true,
    price: 13,
    desc: "地中海式原始美味",
  }, {
    id: 1209,
    name: "本色烤全鱿",
    price: 22,
    desc: "畅享原汁原味之海鲜本色",
  }, {
    id: 1287,
    name: "蒜香烤饼",
    price: 7,
    desc: "小麦的清香融入特制大蒜黄油、唇齿留香",
  }, {
    id: 1286,
    name: "原味烤饼",
    price: 5,
    desc: "手工制作、淳朴清香、口感柔韧",
  }, {
    id: 1288,
    name: "白糖烤饼",
    price: 5,
    desc: "小麦的清香融入淡淡的甜、回味无穷",
  }, {
    id: 1242,
    name: "蒜香烤面包片",
    price: 7,
    desc: "小麦的清香融入特制大蒜黄油、唇齿留香",
  }, {
    id: 1241,
    name: "原味烤面包片",
    price: 5,
    desc: "淳朴清香、口感酥脆",
  }]
}, {
  category: "意面",
  list: [{
    id: 1535,
    name: "酸菜培根意面",
    price: 12,
    spicy: 1,
    desc: "酸爽开胃，体验“酸味人生”"
  }, {
    id: 1525,
    name: "芝士番茄培根意面",
    price: 14,
  }, {
    id: 1541,
    name: "菌菇培根奶油意面",
    price: 14,
  }, {
    id: 1505,
    name: "青酱汁意面",
    price: 14,
    desc: "罗勒与松子等制成的美味诱人的绿色酱汁"
  }, {
    id: 1539,
    name: "麻辣肉酱面(含酸菜)",
    price: 14,
    new: true,
    spicy: 3,
    desc: "麻辣肉酱搭配酸爽的酸菜，麻辣风味十足"
  }, {
    id: 1543,
    name: "曙光女神酱意面",
    new: true,
    price: 16,
    desc: "萨莉亚特制曙光女神酱搭配芝士和菜心"
  }, {
    id: 1512,
    name: "墨鱼汁意面",
    price: 16,
    desc: "新鲜鱿鱼加上墨鱼汁，口味咸鲜、简朴的味道"
  }, {
    id: 1501,
    name: "肉酱意面",
    price: 18,
    desc: "满满的肉酱，意式风味（含猪牛肉）"
  }, {
    id: 1513,
    name: "黑椒牛柳意面",
    price: 18,
    desc: "中西结合、人气美味"
  }, {
    id: 1523,
    name: "蒜香茄汁鲜菇金枪鱼意面",
    spicy: 1,
    price: 18,
    desc: "金枪鱼与各种蘑菇，搭配番茄酱"
  }, {
    id: 1542,
    name: "海鲜蒜香意面",
    new: true,
    spicy: 1,
    price: 18,
    desc: "虾、鱿鱼圈、花蛤加上蒜蓉酱，香气十足"
  }, {
    id: 1509,
    name: "番茄海鲜意面",
    price: 22,
    desc: "虾、花蛤、鱿鱼组成的海鲜盛宴"
  }]
}, {
  category: "米饭",
  list: [{
    id: 1428,
    name: "曙光女神酱烩饭",
    new: true,
    price: 16,
  }, {
    id: 1401,
    name: "海鲜番茄酱烩饭",
    top: true,
    price: 18,
    desc: "浓浓的海鲜味道"
  }, {
    id: 1402,
    name: "芝士肉酱局饭",
    price: 22,
    desc: "香浓的芝士、萨莉亚特别配制的白沙司搭配意式肉酱（含猪牛肉）"
  }, {
    id: 1403,
    name: "肉酱局饭",
    top: true,
    price: 18,
    desc: "萨莉亚特别配制的白沙司搭配意式肉酱（含猪牛肉）"
  }, {
    id: 1415,
    name: "芝士香烤鸡肉局饭",
    price: 22,
    desc: "香浓的芝士、萨莉亚特别配制的白沙司搭配香烤鸡肉"
  }, {
    id: 1416,
    name: "香烤鸡肉局饭",
    price: 18,
    desc: "萨莉亚特别配制的白沙司搭配香烤鸡肉"
  }, {
    id: 1419,
    name: "肉酱香肠芝士烤饭(含酸菜)",
    price: 18,
    desc: "香浓的芝士，酸菜搭配烤肠和肉酱，香味浓郁"
  }, {
    id: 1405,
    name: "鸡肉芝士培根烤饭",
    top: true,
    price: 18,
    desc: "香浓的芝士、玉米、培根、鸡肉与金黄色米饭的结合"
  }, {
    id: 1404,
    name: "鸡排烤饭",
    spicy: 1,
    price: 20,
    desc: "香嫩鸡排搭配金黄色米饭"
  }, {
    id: 1408,
    name: "肉酱局意面",
    price: 18,
    desc: "萨莉亚特别配制的白沙司搭配意式肉酱（含猪牛肉）"
  }, {
    id: 1410,
    name: "海鲜局意面",
    price: 18,
    desc: "萨莉亚特别配制的白沙司搭配海鲜"
  }, {
    id: 1420,
    name: "金枪鱼局意面",
    price: 18,
  }, {
    id: 1409,
    name: "米饭",
    price: 2,
  }]
}, {
  category: "披萨",
  list: [{
    id: 1387,
    name: "榴莲小匹萨(6英寸)",
    top: true,
    price: 21,
    desc: "进口金枕头榴莲与芝士的结合"
  }, {
    id: 1396,
    name: "鸡肉培根小匹萨(6英寸)",
    new: true,
    price: 15,
  }, {
    id: 1395,
    name: "金枪鱼小匹萨(6英寸)",
    new: true,
    price: 15,
    desc: "金枪鱼、玉米与芝士的融合"
  }, {
    id: 1380,
    name: "培根菠萝小匹萨(6英寸)",
    price: 14,
    desc: "熏香培根和菠萝的甜美组合"
  }, {
    id: 1389,
    name: "香肠小匹萨(6英寸)",
    price: 14,
    desc: "香肠、青红椒和芝士的组合"
  }, {
    id: 1393,
    name: "肉酱培根小匹萨（6英寸含酸菜）",
    price: 14,
  }, {
    id: 1382,
    name: "水果小匹萨(6英寸)",
    price: 14,
    desc: "奶酪的浓香包裹水果的甜，“浓情蜜意”"
  }, {
    id: 1307,
    name: "榴莲匹萨(8英寸)",
    price: 39,
    desc: "进口金枕头榴莲与芝士的结合"
  }, {
    id: 1314,
    name: "金枪鱼匹萨(8英寸)",
    new: true,
    price: 26,
    desc: "金枪鱼、玉米与芝士的融合"
  }, {
    id: 1305,
    name: "培根菠萝匹萨(8英寸)",
    recommend: true,
    price: 22,
    desc: "熏香培根和菠萝的甜美组合"
  }]
}, {
  category: "主菜",
  list: [{
    id: 1620,
    name: "蒜香黄油烤鱼排",
    new: true,
    price: 21,
    desc: "蒜香黄油搭配鱼排，鲜香可口"
  }, {
    id: 1606,
    name: "香烤鸡排(黑椒味)",
    price: 18,
    desc: "皮脆肉嫩、原汁原味"
  }, {
    id: 1605,
    name: "香烤鸡排(蒜香味)",
    price: 18,
    desc: "皮脆肉嫩、原汁原味"
  }, {
    id: 1608,
    name: "黑椒烤肠配黑椒鸡排",
    price: 23,
    desc: "烤肠、香烤鸡排和酱汁的组合"
  }, {
    id: 1615,
    name: "五目烤肠配原味鸡排",
    price: 23,
    desc: "烤肠、香烤鸡排和酱汁的组合"
  }, {
    id: 1618,
    name: "黑椒汉堡",
    new: true,
    price: 23,
    desc: "浇有黑椒酱汁、口味平衡香浓"
  }, {
    id: 1619,
    name: "芝士汉堡",
    new: true,
    price: 27,
    desc: "浓浓芝士、番茄酱和汉堡的组合"
  }, {
    id: 1603,
    name: "牛排(黑椒风味)",
    price: 49,
    desc: "精选西冷牛排加上萨莉亚特制酱汁"
  }, {
    id: 1602,
    name: "牛排(蒜香风味)",
    price: 49,
    desc: "精选西冷牛排加上萨莉亚特制酱汁"
  }, {
    id: 1613,
    name: "烘烤羊排(2根)",
    price: 49,
    desc: "精选羔羊羊排、原味烤制"
  }, {
    id: 1601,
    name: "鱿鱼鸡排拼盘",
    price: 36,
    desc: "烤鸡排与烤鱿鱼的人气组合"
  }, {
    id: 1607,
    name: "鸡翅鸡排牛肉粒拼盘",
    price: 49,
    desc: "鸡翅、鸡排及牛肉粒的组合，肉的盛宴"
  }, {
    id: 1612,
    name: "烤肠鸡排羊排拼盘",
    price: 49,
    desc: "羊排、鸡排及烤肠的拼盘，享受分享的乐趣"
  }, {
    id: 1617,
    name: "烤肠鸡排牛肉粒拼盘",
    price: 49,
    desc: "牛肉粒、鸡排及烤肠的拼盘，享受分享的乐趣"
  }]
}, {
  category: "甜点、酒水",
  list: [{
    id: 1888,
    name: "畅饮",
    price: 8,
    desc: "一人畅饮只限一人独享，不可外带"
  }, {
    id: 1736,
    name: "提拉米苏",
    price: 16,
    desc: "马斯卡彭芝士和手指饼融合得恰到好处，顺滑细腻"
  }, {
    id: 1726,
    name: "草莓千层蛋糕",
    price: 16,
    desc: "酸甜可口，幸福的感觉"
  }, {
    id: 1719,
    name: "焦糖布丁",
    price: 16,
    desc: "来自意大利的味道，浓郁奶香，入口即化"
  }, {
    id: 1717,
    name: "激情果粒",
    price: 8,
    desc: "冰激凌同水果的融合，愉悦的回味"
  }, {
    id: 1713,
    name: "芒果布丁",
    top: true,
    price: 8,
    desc: "融在口里，甜在心里"
  }, {
    id: 1731,
    name: "薄脆树莓果酱冰激凌",
    price: 9,
    desc: "香草冰激凌加上薄脆和树莓果酱，酸酸甜甜，香酥可口"
  }, {
    id: 1732,
    name: "薄脆巧克力酱冰激凌",
    price: 9,
    desc: "香草冰激凌加上薄脆和巧克力酱，甜蜜满分，香酥可口"
  }, {
    id: 1735,
    name: "肉桂糖烤饼配香草冰激凌",
    new: true,
    price: 10,
    desc: "散发着香甜肉桂气息的现烤饼底，搭配冰凉香草味冰激凌，感受冷热变化的味觉体验"
  }, {
    id: 1733,
    name: "草莓千层蛋糕配薄脆巧克力酱冰激凌",
    price: 22,
    desc: "草莓千层蛋糕和薄脆巧克力酱冰激凌的酸甜组合"
  }, {
    id: 1737,
    name: "提拉米苏配树莓果酱冰激凌",
    price: 22,
    desc: "提拉米苏和薄脆树莓果酱冰激凌的人气组合"
  }, {
    id: 1738,
    name: "香草冰激凌",
    price: 8,
  }, {
    id: 1908,
    name: "小干红",
    capacity: 187,
    price: 18,
  }, {
    id: 1909,
    name: "小干白",
    capacity: 187,
    price: 18,
    desc: "威尼托产区出品，有清新水果和鲜花的芬芳。"
  }, {
    id: 1921,
    name: "大干红",
    price: 36,
    desc: "威尼托产区出品，有新鲜水果香气，口感浓厚。推荐搭配：奶酪,类、意大利面类\n据《中华人民共和国未成年人保护法》规定，不得向18岁以下未成年人售卖酒精饮料。"
  }, {
    id: 1977,
    name: "蓝布鲁斯科气泡",
    price: 36,
    desc: "莫德纳产区出品，淡柑橘味，甜口清爽。推荐搭配：沙拉类、匹萨,类\n据《中华人民共和国未成年人保护法》规定，不得向18岁以下未成年人售卖酒精饮料。"
  }, {
    id: 1969,
    name: "蒂安诺干红",
    price: 58,
    desc: "托斯卡纳产区出品，香气浓郁，口感浓厚。推荐搭配：肉排类\n据,《中华人民共和国未成年人保护法》规定，不得向18岁以下未成年人售卖酒精饮料。"
  }, {
    id: 1907,
    name: "麒麟啤酒",
    price: 10,
    desc: "据《中华人民共和国未成年人保护法》规定，不得向18岁以下未成,年人售卖酒精饮料。"
  }, {
    id: 1924,
    name: "大干白",
    price: 36,
    desc: "威尼托产区出品，香气浓郁，口感圆润悠长。"
  }]
}, {
  category: "畅饮",
  list: [{
    id: 1888,
    name: "畅饮",
    price: 8,
    desc: "一人畅饮只限一人独享，不可外带"
  }, {
    id: 1777,
    name: "无需畅饮",
    price: 0,
    desc: "冷热水免费，可在畅饮吧自取"
  }]
}]
